"""schema inicial

Revision ID: 814ef37fe5f5
Revises: 
Create Date: 2026-09-18 10:14:38.092666
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('almoxarifados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('regional', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('automacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('gatilho', sa.String(length=80), nullable=False),
    sa.Column('acao', sa.JSON(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=True),
    sa.Column('contato', sa.String(length=120), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=True),
    sa.Column('contato', sa.String(length=120), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materiais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=True),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('unidade', sa.String(length=10), nullable=False),
    sa.Column('estoque_minimo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('parametros_globais',
    sa.Column('chave', sa.String(length=80), nullable=False),
    sa.Column('valor', sa.JSON(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('chave')
    )
    op.create_table('perfis',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('permissoes', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pontos_vegetacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('risco', sa.String(length=20), nullable=False),
    sa.Column('resolvido', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subestacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('operacao_remota_ativa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estoque_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('almoxarifado_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['almoxarifado_id'], ['almoxarifados.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materiais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('almoxarifado_id', 'material_id', name='uq_estoque_almox_material')
    )
    op.create_table('eventos_self_healing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subestacao_id', sa.Integer(), nullable=True),
    sa.Column('ocorrido_em', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('resolvido_automaticamente', sa.Boolean(), nullable=False),
    sa.Column('tempo_restauracao_segundos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subestacao_id'], ['subestacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leituras_subestacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subestacao_id', sa.Integer(), nullable=False),
    sa.Column('registrado_em', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('temperatura_c', sa.Float(), nullable=True),
    sa.Column('carga_percentual', sa.Float(), nullable=True),
    sa.Column('vibracao_mm_s', sa.Float(), nullable=True),
    sa.Column('alerta_gerado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['subestacao_id'], ['subestacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('usuario', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil_id', sa.String(length=40), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_usuario'), 'usuarios', ['usuario'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('bot', sa.String(length=80), nullable=True),
    sa.Column('acao', sa.String(length=120), nullable=False),
    sa.Column('entidade', sa.String(length=60), nullable=False),
    sa.Column('entidade_id', sa.String(length=40), nullable=True),
    sa.Column('antes', sa.JSON(), nullable=True),
    sa.Column('depois', sa.JSON(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('lider_usuario_id', sa.Integer(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lider_usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipe_membros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipe_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('funcao', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wl', sa.String(length=40), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('regional', sa.String(length=60), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('equipe_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('valor_contrato', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('custo_previsto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('custo_realizado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('avanco_previsto', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('avanco_realizado', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('necs_planejados', sa.Integer(), nullable=False),
    sa.Column('necs_executados', sa.Integer(), nullable=False),
    sa.Column('dias_contratada', sa.Integer(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obras_wl'), 'obras', ['wl'], unique=True)
    op.create_table('medicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('contrato', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('percentual', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('responsavel_usuario_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('dias_parada', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ),
    sa.ForeignKeyConstraint(['responsavel_usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('equipe_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('turno', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipes.id'], ),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requisicoes_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitante_usuario_id', sa.Integer(), nullable=True),
    sa.Column('obra_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('observacoes', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ),
    sa.ForeignKeyConstraint(['solicitante_usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('medicao_id', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('percentual_faturado', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('percentual_pago', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['medicao_id'], ['medicoes.id'], ),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requisicao_id', sa.Integer(), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['requisicao_id'], ['requisicoes_compra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requisicao_compra_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requisicao_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materiais.id'], ),
    sa.ForeignKeyConstraint(['requisicao_id'], ['requisicoes_compra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fatura_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=False),
    sa.Column('metodo', sa.String(length=40), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['fatura_id'], ['faturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido_compra_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materiais.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_compra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedido_compra_itens')
    op.drop_table('pagamentos')
    op.drop_table('requisicao_compra_itens')
    op.drop_table('pedidos_compra')
    op.drop_table('faturas')
    op.drop_table('requisicoes_compra')
    op.drop_table('programacoes')
    op.drop_table('medicoes')
    op.drop_index(op.f('ix_obras_wl'), table_name='obras')
    op.drop_table('obras')
    op.drop_table('equipe_membros')
    op.drop_table('equipes')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_usuarios_usuario'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('leituras_subestacao')
    op.drop_table('eventos_self_healing')
    op.drop_table('estoque_itens')
    op.drop_table('subestacoes')
    op.drop_table('pontos_vegetacao')
    op.drop_table('perfis')
    op.drop_table('parametros_globais')
    op.drop_table('materiais')
    op.drop_table('fornecedores')
    op.drop_table('clientes')
    op.drop_table('automacoes')
    op.drop_table('almoxarifados')
    # ### end Alembic commands ###
