"""auth: bloqueio, refresh token, convite, mfa

Revision ID: d0657744bb4f
Revises: 0001
Create Date: 2026-09-18 15:03:07.561108
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revogado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.add_column('usuarios', sa.Column('tentativas_login_falhas', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('usuarios', sa.Column('bloqueado_ate', sa.DateTime(timezone=True), nullable=True))
    op.add_column('usuarios', sa.Column('ultimo_login_em', sa.DateTime(timezone=True), nullable=True))
    op.add_column('usuarios', sa.Column('senha_definida', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('usuarios', sa.Column('convite_token_hash', sa.String(length=64), nullable=True))
    op.add_column('usuarios', sa.Column('convite_expira_em', sa.DateTime(timezone=True), nullable=True))
    op.add_column('usuarios', sa.Column('mfa_habilitado', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('usuarios', sa.Column('mfa_secret', sa.String(length=64), nullable=True))
    with op.batch_alter_table('usuarios') as batch_op:
        batch_op.create_unique_constraint('uq_usuarios_convite_token_hash', ['convite_token_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios') as batch_op:
        batch_op.drop_constraint('uq_usuarios_convite_token_hash', type_='unique')
    op.drop_column('usuarios', 'mfa_secret')
    op.drop_column('usuarios', 'mfa_habilitado')
    op.drop_column('usuarios', 'convite_expira_em')
    op.drop_column('usuarios', 'convite_token_hash')
    op.drop_column('usuarios', 'senha_definida')
    op.drop_column('usuarios', 'ultimo_login_em')
    op.drop_column('usuarios', 'bloqueado_ate')
    op.drop_column('usuarios', 'tentativas_login_falhas')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
